name: Docker crossplatform Build

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: false
      - name: Build
        run: docker build --platform linux/amd64,linux/arm64 -t roboquant/jupyter:latest -f docker/Dockerfile

