name: Warmup MyBinder.org

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://mybinder.org/v2/gh/neurallayer/roboquant-notebook/main?urlpath=lab/tree/tutorials/intro.ipynb'
          method: 'GET'